### ISSUE TITLE
Create phcovid_network module to identify connections between cases

### ISSUE THREAD

**Issue by andrewnyu** [enzoampil/phcovid#9]
Package code for graph traversal to output a table with a.) all networks, b.) cases in the network and c.) size of the network. Goal is to enable analysis on the big transmission networks.

Function:
get_case_network (df, contact_col = 'contacts'):
    return df_case_network

**Comment by andrewnyu** [comment]
Will close this issue with updated pull request:
1. Add phcovid_network module
2. Add numeric versions of case_code column in phcovid.py for processing in phcovid_network functions
3. Fix bug on column rename in phcovid.py

**Comment by enzoampil** [comment]
should be solved by the pull request
